# Generated by Django 4.1.5 on 2023-02-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='bookshelf',
            options={'verbose_name': 'Книжкова полиця', 'verbose_name_plural': 'Книжкові полиці'},
        ),
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.CharField(default=1, max_length=50, verbose_name='Посилання'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
    ]
