# Generated by Django 4.1.5 on 2023-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_book_bookshelf_alter_book_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='Посилання'),
        ),
    ]
