# Generated by Django 4.1.5 on 2023-02-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_book_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bookshelf',
        ),
        migrations.AddField(
            model_name='book',
            name='bookshelf',
            field=models.ManyToManyField(to='main.bookshelf'),
        ),
    ]
