# Generated by Django 4.1.5 on 2023-02-26 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='bookshelf',
            field=models.ManyToManyField(blank=True, to='main.bookshelf'),
        ),
        migrations.AlterField(
            model_name='book',
            name='url_book',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Посилання на книгу'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст статті')),
                ('image', models.ImageField(blank=True, upload_to='article_images/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('books', models.ManyToManyField(related_name='articles', to='main.book')),
                ('categories', models.ManyToManyField(related_name='articles', to='main.articlecategory')),
            ],
        ),
    ]
