# Generated by Django 4.1.5 on 2023-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_articlecategory_alter_book_bookshelf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=250, verbose_name='Тема')),
                ('text', models.TextField(verbose_name='Відгук')),
            ],
        ),
    ]
